# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='estado',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.estado'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estadoper',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.personal'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='idInter',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.interprete'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='idlp',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.localPlataforma'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tiposicion'),
        ),
    ]
