# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171229_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='estadoper',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='idInter',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='idlp',
        ),
        migrations.RemoveField(
            model_name='suplp',
            name='idlop',
        ),
        migrations.AddField(
            model_name='posicion',
            name='estado_maquina',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Estado'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='estado_personal',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Personal'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='interprete',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Interprete'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='localplataforma',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LocalPlataforma'),
        ),
        migrations.AddField(
            model_name='suplp',
            name='localplataforma',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LocalPlataforma'),
        ),
        migrations.AlterField(
            model_name='localplataforma',
            name='local',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Locales'),
        ),
        migrations.AlterField(
            model_name='localplataforma',
            name='plataforma',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Plataforma'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tiposicion'),
        ),
        migrations.AlterField(
            model_name='suplp',
            name='idloc',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.Locales'),
        ),
        migrations.AlterField(
            model_name='suplp',
            name='idpl',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.Plataforma'),
        ),
    ]
