# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171229_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': True, 'verbose_name': 'Estado'},
        ),
        migrations.AlterModelOptions(
            name='locales',
            options={'managed': True, 'verbose_name': 'Locale'},
        ),
        migrations.AlterModelOptions(
            name='localplataforma',
            options={'managed': True, 'verbose_name': 'Local Plataforma'},
        ),
        migrations.AlterModelOptions(
            name='suplp',
            options={'managed': True, 'verbose_name': 'Supervisor Plataforma'},
        ),
        migrations.AlterModelOptions(
            name='tiposicion',
            options={'managed': True, 'verbose_name': 'Tipo de Posicion'},
        ),
        migrations.AddField(
            model_name='interprete',
            name='iden',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='localplataforma',
            name='local',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LocalPlataforma', to='polls.Locales'),
        ),
        migrations.AlterField(
            model_name='localplataforma',
            name='plataforma',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Plataforma'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estado_maquina',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Estado'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estado_personal',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Personal'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='interprete',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Interprete'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='localplataforma',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LocalPlataforma'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tiposicion'),
        ),
        migrations.AlterField(
            model_name='suplp',
            name='idloc',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.Locales'),
        ),
        migrations.AlterField(
            model_name='suplp',
            name='idpl',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='polls.Plataforma'),
        ),
        migrations.AlterField(
            model_name='suplp',
            name='localplataforma',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LocalPlataforma'),
        ),
    ]
